version: "3.4"

volumes:
  pg_data:
    external: false

services:
  
  etl:
    image: "rocker/tidyverse:4.2.1"
    container_name: dfle_etl
    build:
      context: ./ETL
      dockerfile: Dockerfile_ETL
      network: host
    environment:  # reads from local .env file
      - USER=${ETL_USER}
      - PASSWORD=${ETL_PASS}
    working_dir: /dfle_etl/
    volumes:
      - pg_data:/tmp/dfle_pns/

  db:
    image: "postgres:14.4"
    container_name: dfle_db
    restart: always
    environment:  # reads from local .env file
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - "5434:5432"
    working_dir: /pg_data/
    volumes:
      - pg_data:/pg_data/
      - ./ETL/dfle_create_db.sql:/docker-entrypoint-initdb.d/schema.sql

  rstudio:
    image: "rocker/tidyverse:4.2.1"
    container_name: dfle_rstudio
    restart: always
    # depends_on:
    #   - "db"
    environment:  # reads from local .env file
      - USER=${RSTD_USER}
      - PASSWORD=${RSTD_PASS}
      - PG_HOST=${PG_HOST}
      - PG_DB=${PG_DB}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
    build:
      context: ./ETL
      dockerfile: Dockerfile_RStudio
      network: host
    ports:
      - "8787:8787"
    volumes:
      - ./analyses/:/home/rstudio/
      
  pgadmin:
    image: "dpage/pgadmin4"
    container_name: dfle_pgadmin
    environment: # reads from local .env file
      - PGADMIN_DEFAULT_EMAIL=${PGAD_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGAD_PASS}
      - PGADMIN_LISTEN_PORT=${PGAD_PORT}
    # depends_on:
    #   - "db"
    ports:
      - "5050:5050"
    volumes:
      - ./pgadmin4.json:/pgadmin4/servers.json  

