FROM rocker/tidyverse:4.2.1

# update, upgrade system and install additional packages
# RUN apt update -y && apt install wget unzip build-essential -y --no-install-recommends

RUN rm -rf /tmp/dfle_pns/ && mkdir /tmp/dfle_pns

WORKDIR /etl_dfle/

COPY . /etl_dfle/

# ETL
RUN make extract && make transform

